---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd
  namespace: linkerd
spec:
  releaseName: linkerd
  chart:
    spec:
      chart: linkerd2
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
      version: "2.11.1"
  test:
    enable: true
  interval: 1m
  valuesFrom:
    - kind: Secret
      name: linkerd-helm-values
  values:
    installNamespace: false
