---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
  namespace: tempo
spec:
  releaseName: tempo
  chart:
    spec:
      chart: tempo-distributed
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: "0.16.9"
  test:
    enable: true
  dependsOn:
    - name: kube-prometheus-stack
      namespace: kube-prometheus-stack
    - name: thanos
      namespace: kube-prometheus-stack
  interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: tempo-helm-values
  values:
    serviceMonitor:
      enabled: true
    serviceAccount:
      name: tempo
