---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources
  - metrics-server
  - falco
  - linkerd
  - linkerd-viz
  - linkerd-jaeger
  - contour
  - aws-load-balancer-controller
  - kube-prometheus-stack
  - fluent-bit
  - loki
  - tempo
