---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  # - portfolio.yaml
  - metrics-server.yaml
  - falcosecurity.yaml
  - linkerd.yaml
  - bitnami.yaml
  - eks.yaml
  - prometheus-community.yaml
  - fluent.yaml
  - grafana.yaml
