---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  annotations:
    ignore-check.kube-linter.io/no-read-only-root-fs: "This deployment needs write access because it generate nginx.conf"
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        ad.datadoghq.com/nginx.check_names: '["nginx"]'
        ad.datadoghq.com/nginx.init_configs: '[{}]'
        ad.datadoghq.com/nginx.instances: |
          [
            {
              "nginx_status_url":"http://%%host%%:{{ .Values.status.port }}/status"
            }
          ]
        ad.datadoghq.com/nginx.logs: '[{"source":"nginx","service":"portfolio"}]'
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            readOnlyRootFilesystem: false
            runAsNonRoot: true
          env:
            - name: HOST
              value: {{ .Values.host }}
            - name: PORT
              value: "{{ .Values.port }}"
            - name: STATUS_PORT
              value: "{{ .Values.status.port }}"
          ports:
            - containerPort: {{ .Values.port }}
          livenessProbe:
            httpGet:
              path: /status
              port: {{ .Values.status.port }}
          readinessProbe:
            httpGet:
              path: /status
              port: {{ .Values.status.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
