---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: portfolio
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    ignore-check.kube-linter.io/no-read-only-root-fs: paketo-buildpacks/nginx needs write access because it generate nginx.conf
    checkov.io/skip1: CKV_K8S_15=Use IfNotPresent for skaffold dev
    checkov.io/skip2: CKV_K8S_22=paketo-buildpacks/nginx needs write access because it generate nginx.conf
    checkov.io/skip3: CKV_K8S_40=paketo-buildpacks/nginx use 1000 (cnb user) and nginx-prometheus-exporter use 1001
    kube-score/ignore: container-security-context-readonlyrootfilesystem, pod-probes, pod-networkpolicy, container-security-context-user-group-id
    # container-security-context-readonlyrootfilesystem: paketo-buildpacks/nginx needs write access because it generate nginx.conf
    # pod-probes: nginx-prometheus-exporter can't different readiness and liveness probe
    # pod-networkpolicy: kind not support NetworkPolicy
    # https://github.com/kubernetes-sigs/kind/issues/842
    # container-security-context-user-group-id: paketo-buildpacks/nginx use 1000 (cnb user) and nginx-prometheus-exporter use 1001
    polaris.fairwinds.com/deploymentMissingReplicas-exempt: "true" # use HPA
    # paketo-buildpacks/nginx needs write access because it generate nginx.conf
    polaris.fairwinds.com/notReadOnlyRootFilesystem-exempt: "true"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: "runtime/default"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - nginx
              topologyKey: kubernetes.io/hostname
      automountServiceAccountToken: true # for using mTLS of service mesh
      securityContext:
        runAsNonRoot: true
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}@{{ .Values.image.digest | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          securityContext:
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            runAsUser: 1000 # cnb
            capabilities:
              drop:
                - ALL
          env:
            - name: HOST
              value: {{ .Values.host }}
            - name: PORT
              value: "{{ .Values.port }}"
            - name: STATUS_PORT
              value: "{{ .Values.status.port }}"
          ports:
            - name: root
              containerPort: {{ .Values.port }}
            - name: status
              containerPort: {{ .Values.status.port }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - 'ps -A | grep nginx'
          readinessProbe:
            httpGet:
              path: /status
              port: {{ .Values.status.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: nginx-prometheus-exporter
          # nginx/nginx-prometheus-exporter:0.10.0
          image: "nginx/nginx-prometheus-exporter@sha256:1c6eba17d7768401ba1ed056101fc56ec3e3b5c82e508fdd8968fbcd96ec9574"
          imagePullPolicy: Always
          args:
            - -nginx.scrape-uri=http://localhost:{{ .Values.status.port }}/status
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            runAsUser: 1001
            capabilities:
              drop:
                - ALL
          ports:
            - name: exporter
              containerPort: 9113
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9113
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9113
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
              ephemeral-storage: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
              ephemeral-storage: 1Gi
