---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  annotations:
    ignore-check.kube-linter.io/no-read-only-root-fs: "This deployment needs write access because it generate nginx.conf"
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            readOnlyRootFilesystem: false
            runAsNonRoot: true
          env:
            - name: HOST
              value: {{ .Values.host }}
            - name: PORT
              value: "{{ .Values.port }}"
            - name: STATUS_PORT
              value: "{{ .Values.status.port }}"
          ports:
            - containerPort: {{ .Values.port }}
          livenessProbe:
            httpGet:
              path: /status
              port: {{ .Values.status.port }}
          readinessProbe:
            httpGet:
              path: /status
              port: {{ .Values.status.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: nginx-prometheus-exporter
          image: "nginx/nginx-prometheus-exporter:0.9.0"
          args:
            - -nginx.scrape-uri=http://localhost:{{ .Values.status.port }}/status
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          ports:
            - containerPort: 9113
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
