---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.class }}
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: {{ .Values.port }}
  {{- if .Values.ingress.tls }}
      host: {{ $.Values.host }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        - {{ $.Values.host }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
