---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gin
  namespace: portfolio
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gin
