---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: portfolio
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - port: {{ .Values.port }}
      name: main
    - port: {{ .Values.status.port }}
      name: status
    - port: 9113
      name: exporter
  selector:
    app.kubernetes.io/name: nginx
