---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  ports:
    - port: {{ .Values.port }}
      name: main
    - port: {{ .Values.status.port }}
      name: status
    - port: 9113
      name: exporter
  selector:
    app: nginx
