---
apiVersion: v1
kind: Service
metadata:
  name: gin
  namespace: portfolio
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - port: {{ .Values.port }}
      name: public
    - port: {{ .Values.internal.port }}
      name: internal
  selector:
    app.kubernetes.io/name: gin
