{{ if .Values.ingress.virtualService.enabled }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gin
  namespace: portfolio
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.ingress.virtualService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  hosts:
  - {{ .Values.host | quote }}
  gateways:
  - gin
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: gin
        port:
          number: {{ .Values.port }}
{{ end }}
