---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 1m
  dependsOn:
    - name: flagger
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/flux/apps/overlays/production
  prune: true
  wait: true
  timeout: 5m
  healthChecks:
    - apiVersion: flagger.app/v1beta1
      kind: Canary
      name: nginx
      namespace: portfolio
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: loadtester
  namespace: flux-system
spec:
  interval: 1m
  dependsOn:
    - name: flagger
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flagger
    namespace: flux-system
  targetNamespace: portfolio
  path: "./kustomize/tester/"
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: flagger-loadtester
      namespace: portfolio
