---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mesh
  namespace: flux-system
spec:
  interval: 1m
  dependsOn:
    - name: monitoring
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/flux/kustomize/mesh/overlays/production/
  prune: true
