#!/bin/bash

if type pre-commit >/dev/null 2>&1; then
	if ! grep '# File generated by pre-commit: https://pre-commit.com' .git/hooks/pre-commit >/dev/null; then
		pre-commit install --install-hooks
	fi

	if ! grep '# File generated by pre-commit: https://pre-commit.com' .git/hooks/commit-msg >/dev/null; then
		pre-commit install --hook-type commit-msg
	fi
fi
