---
rules:
  no-todo: true
  no-start-duplicated-conjunction: true
  max-number-of-lines: true
  max-comma: true
  no-exclamation-question-mark: true
  period-in-list-item: true
  "@textlint-rule/no-invalid-control-character": true
  "@textlint-rule/no-unmatched-pair": true
  "@textlint-rule/no-duplicate-abbr": true
  unexpanded-acronym:
    ignore_acronyms:
      - CCZE
      - MIT
  abbr-within-parentheses: true
  alex:
    allow:
      - hooks
  write-good: true
  en-max-word-count: true
  stop-words: true
