---
extends: default
rules:
  comments:
    min-spaces-from-content: 1
ignore: |
  misc/pnpm-lock.yaml
  frontend/misc/pnpm-lock.yaml
  infra/charts/*/templates/*.yaml
  infra/charts/*/templates/tests/*.yaml
  infra/flux/clusters/*/flux-system/
