---
apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
    - image: ghcr.io/n4vysh/portfolio
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
        dependencies:
          paths:
            - dist/
            - go.mod
            - go.sum
            - "*.go"
  local:
    push: false
deploy:
  helm:
    releases:
      - name: portfolio
        namespace: portfolio
        artifactOverrides:
          image: ghcr.io/n4vysh/portfolio
        imageStrategy:
          helm: {}
        chartPath: ../infra/charts/portfolio/
        createNamespace: true
