---
apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
    - image: ghcr.io/n4vysh/portfolio
      ko:
        ldflags:
          - -s
          - -w
  local:
    push: false
deploy:
  helm:
    releases:
      - name: portfolio
        namespace: portfolio
        artifactOverrides:
          image: ghcr.io/n4vysh/portfolio
        imageStrategy:
          helm: {}
        chartPath: ../infra/charts/portfolio/
        createNamespace: true
        setValues:
          dev:
            enabled: true
