---
apiVersion: v1
kind: Namespace
metadata:
  name: linkerd-viz
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "linkerd-viz"
    meta.helm.sh/release-namespace: "linkerd-viz"
