---
host: localhost
port: 8080
internal:
  port: 8081
mode: release
image:
  # ghcr.io/n4vysh/portfolio:bb14505
  repository: ghcr.io/n4vysh/portfolio
  # yamllint disable-line rule:line-length
  digest: sha256:34817454a803d87e97d4e415bfefabde28b5a5c8b2a3d173bdf975dacef41c08

labels:
  app.kubernetes.io/name: gin
  app.kubernetes.io/instance: gin
  app.kubernetes.io/version: 1.7.7
  app.kubernetes.io/component: web-server
  app.kubernetes.io/part-of: portfolio
  app.kubernetes.io/managed-by: helm

ingress:
  annotations: {}
  class: contour
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
    ephemeral-storage: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi
    ephemeral-storage: 1Gi

autoscaling:
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

trace:
  enabled: false

metrics:
  serviceMonitor:
    enabled: false
