---
host: n4vysh.dev
port: 8080
internal:
  port: 8081
image:
  repository: ghcr.io/n4vysh/portfolio
  # yamllint disable-line rule:line-length
  digest: sha256:1b95ae3594d1052495271459367a62cd24a745610ae0fbc42adb84e420fc700f

dev:
  enabled: false

labels:
  app.kubernetes.io/name: gin
  app.kubernetes.io/instance: gin
  app.kubernetes.io/version: 1.7.7
  app.kubernetes.io/component: web-server
  app.kubernetes.io/part-of: portfolio
  app.kubernetes.io/managed-by: helm

ingress:
  enabled: false
  annotations: {}
  class: ""
  tls: []
  gateway:
    enabled: true
    annotations: {}
    selector: ingressgateway
  virtualService:
    enabled: true
    annotations: {}

resources:
  limits:
    cpu: 100m
    memory: 128Mi
    ephemeral-storage: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi
    ephemeral-storage: 1Gi

autoscaling:
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

trace:
  enabled: false

metrics:
  serviceMonitor:
    enabled: false
