---
host: localhost
port: 8080
status:
  port: 8081
image:
  repository: ghcr.io/n4vysh/portfolio
  pullPolicy: IfNotPresent
  tag: "bb14505"

ingress:
  annotations: {}
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
