---
host: localhost
port: 8080
status:
  port: 8081
image:
  repository: ghcr.io/n4vysh/portfolio
  pullPolicy: IfNotPresent
  tag: "bb14505"

labels:
  app.kubernetes.io/name: nginx
  app.kubernetes.io/instance: nginx
  app.kubernetes.io/version: 1.21.4
  app.kubernetes.io/component: web-server
  app.kubernetes.io/part-of: portfolio
  app.kubernetes.io/managed-by: helm

ingress:
  annotations: {}
  class: ""
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

servicemonitor: false
