---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  releaseName: loki
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: "2.8.4"
  test:
    enable: true
  dependsOn:
    - name: kube-prometheus-stack
      namespace: kube-prometheus-stack
    - name: thanos
      namespace: kube-prometheus-stack
  interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: loki-helm-values
  values:
    serviceMonitor:
      enabled: true
    serviceAccount:
      name: loki
    config:
      compactor:
        shared_store: s3
        compaction_interval: 10m
        retention_enabled: true
        retention_delete_delay: 2h
        retention_delete_worker_count: 150
      limits_config:
        # NOTE: The minimum retention period is 24h.
        # https://grafana.com/docs/loki/latest/operations/storage/retention/
        retention_period: 24h
      schema_config:
        configs:
          # https://github.com/fluxcd/helm-controller/issues/293
          - from: "2020-10-24"
            store: boltdb-shipper
            object_store: s3
            schema: v11
            index:
              prefix: index_
              period: 24h
      storage_config:
        boltdb_shipper:
          shared_store: s3
        aws:
          s3forcepathstyle: true
