---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portfolio
  namespace: portfolio
spec:
  releaseName: portfolio
  chart:
    spec:
      chart: ./infra/charts/portfolio
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  test:
    enable: true
  interval: 1m
