---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco
  namespace: falco
spec:
  releaseName: falco
  chart:
    spec:
      chart: falco
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: flux-system
      version: "1.17.3"
  test:
    enable: true
  interval: 1m
  values:
    # https://github.com/bottlerocket-os/bottlerocket/issues/862
    docker:
      enabled: false
    ebpf:
      enabled: true
    falco:
      grpc:
        enabled: true
      grpcOutput:
        enabled: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco-exporter
  namespace: falco
spec:
  releaseName: falco-exporter
  chart:
    spec:
      chart: falco-exporter
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: flux-system
      version: "0.8.0"
  test:
    enable: true
  dependsOn:
    - name: falco
  interval: 1m
