---
apiVersion: v1
kind: Namespace
metadata:
  name: linkerd-jaeger
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "linkerd-jaeger"
    meta.helm.sh/release-namespace: "linkerd-jaeger"
