---
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jetstack
    url: https://charts.jetstack.io
helmDefaults:
  createNamespace: true
  timeout: 30
environments:
  development:
  staging:
    values:
      - ./values/{{ .Environment.Name }}/portfolio.yaml
    secrets:
      - ./secrets/cloudflare.enc.yaml
  production:
    values:
      - ./values/{{ .Environment.Name }}/portfolio.yaml
    secrets:
      - ./secrets/cloudflare.enc.yaml
releases:
  - name: contour
    namespace: contour
    chart: bitnami/contour
    version: 7.0.5
    values:
      - ./values/{{ .Environment.Name }}/contour.yaml
  - name: external-dns
    namespace: external-dns
    chart: bitnami/external-dns
    version: 5.5.2
    installed: {{ or (eq .Environment.Name "staging") (eq .Environment.Name "production") | toYaml }}
    values:
      - ./values/external-dns.yaml.gotmpl
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.6.1
    needs:
      - contour
    installed: {{ or (eq .Environment.Name "staging") (eq .Environment.Name "production") | toYaml }}
  - name: portfolio
    namespace: portfolio
    chart: ../charts/portfolio/
    values:
      - ./values/portfolio.yaml.gotmpl
    needs:
      - contour
      - cert-manager
