---
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jetstack
    url: https://charts.jetstack.io
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server/
  - name: falcosecurity
    url: https://falcosecurity.github.io/charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
helmDefaults:
  createNamespace: true
  timeout: 30
environments:
  development:
  staging:
    values:
      - ./values/{{ .Environment.Name }}/portfolio.yaml
    secrets:
      - ./secrets/cloudflare.enc.yaml
      - ./secrets/grafana-cloud.enc.yaml
  production:
    values:
      - ./values/{{ .Environment.Name }}/portfolio.yaml
    secrets:
      - ./secrets/cloudflare.enc.yaml
      - ./secrets/grafana-cloud.enc.yaml
releases:
  - name: contour
    namespace: contour
    chart: bitnami/contour
    version: 7.0.8
    values:
      - ./values/{{ .Environment.Name }}/contour.yaml
  - name: external-dns
    namespace: external-dns
    chart: bitnami/external-dns
    version: 5.5.2
    installed: {{ or (eq .Environment.Name "staging") (eq .Environment.Name "production") | toYaml }}
    values:
      - ./values/external-dns.yaml.gotmpl
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.6.1
    needs:
      - contour
    installed: {{ or (eq .Environment.Name "staging") (eq .Environment.Name "production") | toYaml }}
  - name: metrics-server
    namespace: metrics-server
    chart: metrics-server/metrics-server
    version: 3.7.0
  - name: falco
    namespace: falco
    chart: falcosecurity/falco
    version: 1.16.3
    installed: {{ or (eq .Environment.Name "staging") (eq .Environment.Name "production") | toYaml }}
  - name: kube-prometheus-stack
    namespace: kube-prometheus-stack
    chart: prometheus-community/kube-prometheus-stack
    version: 25.2.0
    installed: {{ or (eq .Environment.Name "staging") (eq .Environment.Name "production") | toYaml }}
    values:
      - ./values/kube-prometheus-stack.yaml.gotmpl
    disableValidationOnInstall: true
    timeout: 300
  - name: portfolio
    namespace: portfolio
    chart: ../charts/portfolio/
    values:
      - ./values/portfolio.yaml.gotmpl
    needs:
      - contour
      - cert-manager
      - kube-prometheus-stack
