thanos:
    aws:
        s3:
            accesskey: ENC[AES256_GCM,data:tQQDrJxaY8id0CrRwKRdtnk1uzQ=,iv:rc6VAvIYmRR8vYeRPfyoYkhQ7d/uGLRinIAT4JiiEAk=,tag:9fe+LZgbDDEZ1uqNL7i3GA==,type:str]
            secretkey: ENC[AES256_GCM,data:clpnz51W52SukTVJYo08/dU0sbYJxSle75Cnu4X32+XFiKEHMYTORQ==,iv:rOHE7mXXadq5xmHMkAQDGQH0loiPYZteVBuCNp5RwKQ=,tag:9bqioK70RNas4q36MZaQoA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-1:746269319114:key/mrk-ada43909b95b46dbb9d2efddc592566e
          created_at: "2022-01-02T09:51:21Z"
          enc: AQICAHj89xp8cGPUqVqjKH3z0m9ktuR1rkQYpz8FfGCm2exWDQEMH3FcPD2ByV7Aj2rt0pfdAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM3cNhXd50Jafb2YsvAgEQgDsaEgQMV1GL4/pg0gLA1+PPXKRdwW1DKui6kKnoV2hTVF5dgpX8507UT0OULYvMGPKDBuliSsd0sPHkAA==
          aws_profile: ""
        - arn: arn:aws:kms:us-east-1:746269319114:key/mrk-ada43909b95b46dbb9d2efddc592566e
          created_at: "2022-01-02T09:51:21Z"
          enc: AQICAHj89xp8cGPUqVqjKH3z0m9ktuR1rkQYpz8FfGCm2exWDQG1txZ1RHKbo3shit9f/ojmAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBygGfB5NMuaH1d3GAgEQgDtmXtLvRvH3cPUpwJfoTOtytZP3hCFOmRLQTjQdOCAqurfR6AA4uo7kDl31QvXDpWdqLwbsKU51ve/2Gw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-02T14:14:22Z"
    mac: ENC[AES256_GCM,data:O2xTMtQXk2qIrsy3iYJoJteYEaYRyCvGEgYoRVqak/mRsacH8Mea/SRgWzAB48OEJm/FqrAV+1Cisn+1wBnSy6tiJEZ69Ypsp5+VLIGs/9RP5tSifTdKWggoFUMDRfpAOVS7A37YK0K2bg72RUEy2Z+6s+6QqrB3UkSXTrvlMEY=,iv:gNWmA3vdXf6pOI/IAoHZ7mjhDDZf94YZFtj/pNvBRqc=,tag:ysOSbujiQi/uyyLVJgxjfQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
