---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: fluent-bit
spec:
  releaseName: fluent-bit
  chart:
    spec:
      chart: fluent-bit
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: flux-system
      version: "0.19.15"
  test:
    enable: true
  dependsOn:
    - name: kube-prometheus-stack
      namespace: kube-prometheus-stack
    - name: thanos
      namespace: kube-prometheus-stack
    - name: loki
      namespace: loki
  interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: fluent-bit-helm-values
  values:
    serviceMonitor:
      enabled: true
    dashboards:
      enabled: true
      namespace: kube-prometheus-stack
