---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco-exporter
  namespace: falco
spec:
  values:
    serviceMonitor:
      enabled: true
    grafanaDashboard:
      enabled: true
      namespace: kube-prometheus-stack
