---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: portfolio
nodes:
  - role: worker
    image: kindest/node:v1.21.1
  - role: control-plane
    image: kindest/node:v1.21.1
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 30000
        hostPort: 80
        protocol: TCP
