---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portfolio
  namespace: portfolio
spec:
  values:
    ingress:
      gateway:
        enabled: false
      virtualService:
        enabled: false
    metrics:
      serviceMonitor:
        enabled: true
    trace:
      enabled: true
      protocol: http/protobuf
      endpoint: http://tempo-tempo-distributed-distributor.tempo:55681/v1/traces
