---
host: localhost
port: 8080
image:
  repository: ghcr.io/n4vysh/portfolio
  pullPolicy: IfNotPresent
  tag: "cf63a6e"

ingress:
  annotations:
    {}
    # cert-manager.io/cluster-issuer: letsencrypt-staging
    # ingress.kubernetes.io/force-ssl-redirect: "true"
    # kubernetes.io/ingress.class: contour
    # kubernetes.io/tls-acme: "true"
  tls: []
  #  - secretName: portfolio-tls

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
