---
portfolio:
  host: n4vysh.dev
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      kubernetes.io/ingress.class: contour
      external-dns.alpha.kubernetes.io/ttl: "3600"
    tls:
      - secretName: portfolio-tls
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
