---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali-operator
  namespace: kiali-operator
spec:
  releaseName: kiali-operator
  chart:
    spec:
      chart: kiali-operator
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: flux-system
      version: "1.50.0"
  test:
    enable: true
  interval: 1m
  dependsOn:
    - name: istiod
      namespace: istio-system
  values:
    cr:
      create: true
      namespace: istio-system
