---
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
environments:
  {{ .Environment.Name }}:
    values:
      - ./environments/values/{{ .Environment.Name }}/contour.yaml
releases:
  - name: contour
    namespace: contour
    chart: bitnami/contour
    version: 7.0.7
    values:
      - ./values/templates/contour.yaml.gotmpl
