---
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: portfolio
  namespace: portfolio
spec:
  routes:
    - condition:
        method: GET
        pathRegex: /
      name: GET /
    - condition:
        method: GET
        pathRegex: /healthz
      name: GET /healthz
    - condition:
        method: GET
        pathRegex: /readyz
      name: GET /readyz
    - condition:
        method: GET
        pathRegex: /metrics
      name: GET /metrics
