---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: n4vysh@n4vysh.dev
    server: {{ .Values.acme.server }}
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: {{ .Values.ingress.class }}
          ingressTemplate:
            metadata:
              annotations:
                ingress.kubernetes.io/force-ssl-redirect: "true"
