---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  releaseName: istio-base
  chart:
    spec:
      chart: base
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      version: "1.13.3"
  test:
    enable: true
  interval: 1m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  releaseName: istiod
  chart:
    spec:
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      version: "1.13.3"
  test:
    enable: true
  interval: 1m
  dependsOn:
    - name: istio-base
      namespace: istio-system
  values:
    global:
      logAsJson: true
    meshConfig:
      enableTracing: true
      defaultConfig:
        tracing:
          sampling: 100.0
          zipkin:
            address: tempo-tempo-distributed-distributor.tempo:9411
      accessLogFile: /dev/stdout
      accessLogEncoding: JSON
      # yamllint disable rule:line-length
      accessLogFormat: |
        {
          "authority": "%REQ(:AUTHORITY)%",
          "bytes_received": "%BYTES_RECEIVED%",
          "bytes_sent": "%BYTES_SENT%",
          "connection_termination_details": "%CONNECTION_TERMINATION_DETAILS%",
          "downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS%",
          "downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%",
          "duration": "%DURATION%",
          "method": "%REQ(:METHOD)%",
          "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
          "protocol": "%PROTOCOL%",
          "requested_server_name": "%REQUESTED_SERVER_NAME%",
          "response_code": "%RESPONSE_CODE%",
          "response_code_details": "%RESPONSE_CODE_DETAILS%",
          "response_flags": "%RESPONSE_FLAGS%",
          "route_name": "%ROUTE_NAME%",
          "start_time": "%START_TIME%",
          "upstream_cluster": "%UPSTREAM_CLUSTER%",
          "upstream_host": "%UPSTREAM_HOST%",
          "upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS%",
          "upstream_service_time": "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%",
          "upstream_transport_failure_reason": "%UPSTREAM_TRANSPORT_FAILURE_REASON%",
          "user_agent": "%REQ(USER-AGENT)%",
          "x_forwarded_for": "%REQ(X-FORWARDED-FOR)%",
          "x_request_id": "%REQ(X-REQUEST-ID)%",
          "x_b3_traceid": "%REQ(x-b3-traceid)%"
        }
      # yamllint enable rule:line-length
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-system
spec:
  releaseName: istio-ingress
  chart:
    spec:
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      version: "1.13.3"
  test:
    enable: true
  dependsOn:
    - name: istiod
      namespace: istio-system
  interval: 1m
  values:
    service:
      type: ClusterIP
      externalTrafficPolicy: null
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: target-group-bindings
  namespace: istio-system
spec:
  releaseName: target-group-bindings
  chart:
    spec:
      chart: ./infra/charts/target-group-bindings
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  test:
    enable: true
  dependsOn:
    - name: istio-ingress
      namespace: istio-system
  interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: target-group-bindings-helm-values
  values:
    service:
      name: istio-ingress
      namespace: istio-system
