---
name: main
"on": push
jobs:
  install-packages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        uses: ./.github/actions/install-packages
  set-pre-commit-info:
    runs-on: ubuntu-20.04
    outputs:
      hooks: ${{ steps.output-pre-commit-info.outputs.hooks }}
    steps:
      - uses: actions/checkout@v2
      - id: output-pre-commit-info
        run: .github/scripts/output-pre-commit-info.bash
  pre-commit:
    runs-on: ubuntu-20.04
    needs:
      - install-packages
      - set-pre-commit-info
    strategy:
      fail-fast: false
      matrix:
        hook: ${{ fromJson(needs.set-pre-commit-info.outputs.hooks) }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        uses: ./.github/actions/install-packages
      - name: Run pre-commit hooks
        run: |
          eval "$(direnv export bash)"
          just check ${{ matrix.hook }}
  deploy-prd:
    # yamllint disable-line rule:line-length
    uses: n4vysh/portfolio/.github/workflows/reusable-terragrunt-workflow.yml@main
    with:
      environment: production
      url: https://n4vysh.dev
      # yamllint disable-line rule:line-length
      role-to-assume: arn:aws:iam::804137327620:role/prd-portfolio-github-actions
    needs:
      - install-packages
      - pre-commit
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
  deploy-stg:
    # yamllint disable-line rule:line-length
    uses: n4vysh/portfolio/.github/workflows/reusable-terragrunt-workflow.yml@main
    with:
      environment: staging
      url: https://stg.n4vysh.dev
      role-to-assume: dummy-arn
    needs:
      - install-packages
      - pre-commit
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
  container-image-deploy:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    needs:
      - pre-commit
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        uses: ./.github/actions/install-packages
      - name: Build icon image
        run: |
          cd frontend/
          eval "$(direnv export bash)"
          just build-icon-image
      - name: Build a static site
        run: |
          cd frontend/
          eval "$(direnv export bash)"
          just build-static-site
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push container image
        run: |
          cd frontend/
          eval "$(direnv export bash)"
          just build-push-container-image
  chart-release:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    needs:
      - pre-commit
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1
      - uses: helm/chart-releaser-action@v1.2.1
        with:
          charts_dir: infra/charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
