---
name: main
"on": push
jobs:
  install-packages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        uses: ./.github/actions/install-packages
  set-pre-commit-info:
    runs-on: ubuntu-20.04
    outputs:
      hooks: ${{ steps.output-pre-commit-info.outputs.hooks }}
    steps:
      - uses: actions/checkout@v2
      - id: output-pre-commit-info
        run: .github/scripts/output-pre-commit-info.bash
  pre-commit:
    runs-on: ubuntu-20.04
    needs:
      - install-packages
      - set-pre-commit-info
    strategy:
      fail-fast: false
      matrix:
        hook: ${{ fromJson(needs.set-pre-commit-info.outputs.hooks) }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        uses: ./.github/actions/install-packages
      - name: Run pre-commit hooks
        run: |
          eval "$(direnv export bash)"
          just check ${{ matrix.hook }}
  set-terragrunt-info:
    runs-on: ubuntu-20.04
    outputs:
      environments: ${{ steps.output-terragrunt-info.outputs.environments }}
    steps:
      - uses: actions/checkout@v2
      - id: output-terragrunt-info
        run: .github/scripts/output-terragrunt-info.bash
  terragrunt-plan:
    runs-on: ubuntu-20.04
    needs:
      - install-packages
      - set-terragrunt-info
      - pre-commit
    strategy:
      fail-fast: false
      matrix:
        # yamllint disable-line rule:line-length
        environments: ${{ fromJson(needs.set-terragrunt-info.outputs.environments) }}
    environment:
      name: ${{ matrix.environments }}
      url: |
        ${{
          (matrix.environments == 'production' && 'https://n4vysh.dev')
          || (matrix.environments == 'staging' && 'https://stg.n4vysh.dev')
        }}
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        uses: ./.github/actions/install-packages
      - name: Configure AWS Credentials (production)
        uses: ./.github/actions/configure-aws-credentials
        if: matrix.environments == 'production'
        with:
          # yamllint disable-line rule:line-length
          role-to-assume: arn:aws:iam::804137327620:role/prd-portfolio-github-actions
      - name: Run driftctl
        env:
          ENV: ${{ matrix.environments }}
        run: |
          eval "$(direnv export bash)"
          ./scripts/driftctl.bash
        working-directory: ./infra/terragrunt/
      - name: Start kind mock cluster
        env:
          ENV: ${{ matrix.environments }}
        run: |
          eval "$(direnv export bash)"
          ./scripts/start-kind-mock-cluster.bash
        working-directory: ./infra/terragrunt/
      - name: Run terragrunt plan
        env:
          ENV: ${{ matrix.environments }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
        run: |
          eval "$(direnv export bash)"
          just plan
        working-directory: ./infra/terragrunt/
      - name: Stop kind mock cluster
        env:
          ENV: ${{ matrix.environments }}
        run: |
          eval "$(direnv export bash)"
          ./scripts/stop-kind-mock-cluster.bash
        working-directory: ./infra/terragrunt/
  terragrunt-apply:
    runs-on: ubuntu-20.04
    needs:
      - install-packages
      - set-terragrunt-info
      - pre-commit
      - terragrunt-plan
    strategy:
      fail-fast: false
      matrix:
        # yamllint disable-line rule:line-length
        environments: ${{ fromJson(needs.set-terragrunt-info.outputs.environments) }}
    environment:
      name: ${{ matrix.environments }}
      url: |
        ${{
          (matrix.environments == 'production' && 'https://n4vysh.dev')
          || (matrix.environments == 'staging' && 'https://stg.n4vysh.dev')
        }}
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        uses: ./.github/actions/install-packages
      - name: Configure AWS Credentials (production)
        uses: ./.github/actions/configure-aws-credentials
        if: matrix.environments == 'production'
        with:
          # yamllint disable-line rule:line-length
          role-to-assume: arn:aws:iam::804137327620:role/prd-portfolio-github-actions
      - name: Run terragrunt apply
        env:
          ENV: ${{ matrix.environments }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
        run: |
          eval "$(direnv export bash)"
          just apply
        working-directory: ./infra/terragrunt/
  container-image-deploy:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    needs:
      - pre-commit
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        uses: ./.github/actions/install-packages
      - name: Build icon image
        run: |
          cd frontend/
          eval "$(direnv export bash)"
          just build-icon-image
      - name: Build a static site
        run: |
          cd frontend/
          eval "$(direnv export bash)"
          just build-static-site
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push container image
        run: |
          cd frontend/
          eval "$(direnv export bash)"
          just build-push-container-image
  chart-release:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    needs:
      - pre-commit
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1
      - uses: helm/chart-releaser-action@v1.2.1
        with:
          charts_dir: infra/charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
