---
name: main
"on": push
jobs:
  icon:
    uses: n4vysh/portfolio/.github/workflows/reusable-pre-commit-run.yml@main
    with:
      hook: icon
      setup-rust: true
  frontend:
    uses: n4vysh/portfolio/.github/workflows/reusable-pre-commit-run.yml@main
    with:
      hook: frontend
      setup-deno: true
      setup-just: true
      setup-frontend-packages: true
  config:
    uses: n4vysh/portfolio/.github/workflows/reusable-pre-commit-run.yml@main
    with:
      hook: config
      setup-just: true
  container:
    uses: n4vysh/portfolio/.github/workflows/reusable-pre-commit-run.yml@main
    with:
      hook: container
      setup-just: true
      setup-skaffold: true
  markup:
    uses: n4vysh/portfolio/.github/workflows/reusable-pre-commit-run.yml@main
    with:
      hook: markup
  shell-scripts:
    uses: n4vysh/portfolio/.github/workflows/reusable-pre-commit-run.yml@main
    with:
      hook: shell-scripts
      setup-rust: true
  git:
    uses: n4vysh/portfolio/.github/workflows/reusable-pre-commit-run.yml@main
    with:
      hook: git
  file:
    uses: n4vysh/portfolio/.github/workflows/reusable-pre-commit-run.yml@main
    with:
      hook: file
  text:
    uses: n4vysh/portfolio/.github/workflows/reusable-pre-commit-run.yml@main
    with:
      hook: text
  ci:
    uses: n4vysh/portfolio/.github/workflows/reusable-pre-commit-run.yml@main
    with:
      hook: ci
  artifact:
    uses: n4vysh/portfolio/.github/workflows/reusable-pre-commit-run.yml@main
    with:
      hook: artifact
  deploy:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    needs:
      - icon
      - frontend
      - config
      - container
      - markup
      - shell-scripts
      - git
      - file
      - text
      - ci
      - artifact
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: hiberbee/github-action-skaffold@1.14.0
        with:
          skaffold-version: 1.35.0
          command: build
          filename: manifests/skaffold.yaml
          push: true
