---
name: main
"on": push
jobs:
  frontend:
    uses: n4vysh/portfolio/.github/workflows/reusable-pre-commit-run.yml@main
    with:
      hook: frontend
      setup-deno: true
      setup-just: true
      setup-frontend-packages: true
  config:
    uses: n4vysh/portfolio/.github/workflows/reusable-pre-commit-run.yml@main
    with:
      hook: config
      setup-just: true
  container:
    uses: n4vysh/portfolio/.github/workflows/reusable-pre-commit-run.yml@main
    with:
      hook: container
      setup-just: true
      setup-skaffold: true
  markup:
    uses: n4vysh/portfolio/.github/workflows/reusable-pre-commit-run.yml@main
    with:
      hook: markup
  shell-scripts:
    uses: n4vysh/portfolio/.github/workflows/reusable-pre-commit-run.yml@main
    with:
      hook: shell-scripts
      setup-rust: true
  git:
    uses: n4vysh/portfolio/.github/workflows/reusable-pre-commit-run.yml@main
    with:
      hook: git
  file:
    uses: n4vysh/portfolio/.github/workflows/reusable-pre-commit-run.yml@main
    with:
      hook: file
  text:
    uses: n4vysh/portfolio/.github/workflows/reusable-pre-commit-run.yml@main
    with:
      hook: text
  ci:
    uses: n4vysh/portfolio/.github/workflows/reusable-pre-commit-run.yml@main
    with:
      hook: ci
  artifact:
    uses: n4vysh/portfolio/.github/workflows/reusable-pre-commit-run.yml@main
    with:
      hook: artifact
      setup-skaffold: true
  deploy:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    needs:
      - frontend
      - config
      - container
      - markup
      - shell-scripts
      - git
      - file
      - text
      - ci
      - artifact
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: 1.16.2
      - uses: extractions/setup-just@v1
        with:
          just-version: 0.10.3
      - name: Setup frontend packages
        run: just init
      - name: Build images
        run: just build-images
      - name: Build a static site
        run: just build-static-site
      - id: var
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: hiberbee/github-action-skaffold@1.14.0
        with:
          skaffold-version: 1.35.0
          command: build
          filename: manifests/skaffold.yaml
          push: true
          tag: ${{ steps.var.outputs.sha_short }}
